-- MimiiHub Supabase schema.
-- Run this migration in the Supabase SQL editor before using the storefront.

create table if not exists public.categories (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  image text,
  created_at timestamptz not null default now()
);

create table if not exists public.subcategories (
  id integer generated by default as identity primary key,
  category_id integer not null references public.categories(id) on delete cascade,
  name text not null,
  slug text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  price double precision not null,
  discount_pct double precision,
  images text[] not null default '{}',
  cover_image text,
  category_id integer references public.categories(id) on delete set null,
  subcategory_id integer references public.subcategories(id) on delete set null,
  stock_qty integer not null default 0,
  in_stock boolean not null default true,
  visible boolean not null default true,
  featured boolean not null default false,
  new_arrival boolean not null default false,
  best_seller boolean not null default false,
  specs jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id integer generated by default as identity primary key,
  username text not null unique,
  password_hash text,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id integer generated by default as identity primary key,
  order_ref text not null unique,
  full_name text not null,
  phone text not null,
  state text not null,
  city text not null,
  address text not null,
  items jsonb not null default '[]'::jsonb,
  subtotal double precision not null,
  payment_method text not null,
  payment_status text not null default 'Awaiting Payment',
  order_status text not null default 'Awaiting Payment',
  flutterwave_ref text,
  timeline jsonb not null default '[]'::jsonb,
  user_id integer references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  id integer generated by default as identity primary key,
  key text not null unique,
  value jsonb not null
);

create index if not exists products_category_id_idx on public.products(category_id);
create index if not exists products_subcategory_id_idx on public.products(subcategory_id);
create index if not exists products_visible_idx on public.products(visible);
create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists orders_order_ref_idx on public.orders(order_ref);

alter table public.categories enable row level security;
alter table public.subcategories enable row level security;
alter table public.products enable row level security;
alter table public.users enable row level security;
alter table public.orders enable row level security;
alter table public.settings enable row level security;

-- This app currently has no admin authentication. These policies preserve the
-- existing public admin behavior while keeping the service-role key server-only.
drop policy if exists "MimiiHub public access" on public.categories;
create policy "MimiiHub public access" on public.categories for all to anon, authenticated using (true) with check (true);
drop policy if exists "MimiiHub public access" on public.subcategories;
create policy "MimiiHub public access" on public.subcategories for all to anon, authenticated using (true) with check (true);
drop policy if exists "MimiiHub public access" on public.products;
create policy "MimiiHub public access" on public.products for all to anon, authenticated using (true) with check (true);
drop policy if exists "MimiiHub public access" on public.users;
create policy "MimiiHub public access" on public.users for all to anon, authenticated using (true) with check (true);
drop policy if exists "MimiiHub public access" on public.orders;
create policy "MimiiHub public access" on public.orders for all to anon, authenticated using (true) with check (true);
drop policy if exists "MimiiHub public access" on public.settings;
create policy "MimiiHub public access" on public.settings for all to anon, authenticated using (true) with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 10485760, array['image/*'])
on conflict (id) do update set public = true, file_size_limit = 10485760, allowed_mime_types = array['image/*'];

drop policy if exists "MimiiHub product image access" on storage.objects;
create policy "MimiiHub product image access" on storage.objects for all to anon, authenticated
using (bucket_id = 'product-images') with check (bucket_id = 'product-images');